globalvar enemies;
enemies = [];
var E = ENEMY_BASIC;
	enemies[E, HP] = 3;
	enemies[E, SPEED] = 5;
	enemies[E, DEFENSE] = 0;
	enemies[E, SPRITE] = Spr_viroid;
var E = ENEMY_VIRUS;
	enemies[E, HP] = 3;
	enemies[E, SPEED] = 5;
	enemies[E, DEFENSE] = 0;
	enemies[E, SPRITE] = spr_virus;
